default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: danshortener_development
test:
  <<: *default
  database: danshortener_test

production:
  <<: *default
  database: danshortener_production
